import { Router } from 'express';
import { authRouter } from './modules/auth/auth.routes.js';
import { usersRouter } from './modules/users/users.routes.js';
import { rolesRouter } from './modules/roles/roles.routes.js';
import { permissionsRouter } from './modules/permissions/permissions.routes.js';
import { ownersRouter } from './modules/owners/owners.routes.js';
import { patientsRouter } from './modules/patients/patients.routes.js';
import { calendarRouter } from './modules/calendar/calendar.routes.js';
import { appointmentsRouter } from './modules/appointments/appointments.routes.js';
import { dashboardRouter } from './modules/dashboard/dashboard.routes.js';
import { servicesRouter } from './modules/services/services.routes.js';
import { suppliersRouter } from './modules/suppliers/suppliers.routes.js';
import { drugsRouter } from './modules/drugs/drugs.routes.js';
import { warehouseRouter } from './modules/warehouse/warehouse.routes.js';
import { invoicesRouter } from './modules/invoices/invoices.routes.js';
import { debtsRouter } from './modules/debts/debts.routes.js';
import { reportsRouter } from './modules/reports/reports.routes.js';
import { vaccinationsRouter } from './modules/vaccinations/vaccinations.routes.js';
import { filesRouter } from './modules/files/files.routes.js';
import { templatesRouter } from './modules/templates/templates.routes.js';
import { remindersRouter } from './modules/reminders/reminders.routes.js';
import { salaryRouter } from './modules/salary/salary.routes.js';
import { discountRouter } from './modules/discount/discount.routes.js';
import { settingsRouter } from './modules/settings/settings.routes.js';
import { clientRouter } from './modules/client/client.routes.js';
import { exportsRouter } from './modules/exports/exports.routes.js';
import { importsRouter } from './modules/imports/imports.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/permissions', permissionsRouter);
apiRouter.use('/owners', ownersRouter);
apiRouter.use('/patients', patientsRouter);
apiRouter.use('/calendar', calendarRouter);
apiRouter.use('/appointments', appointmentsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/services', servicesRouter);
apiRouter.use('/suppliers', suppliersRouter);
apiRouter.use('/drugs', drugsRouter);
apiRouter.use('/warehouse', warehouseRouter);
apiRouter.use('/invoices', invoicesRouter);
apiRouter.use('/debts', debtsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/vaccinations', vaccinationsRouter);
apiRouter.use('/files', filesRouter);
apiRouter.use('/templates', templatesRouter);
apiRouter.use('/reminders', remindersRouter);
apiRouter.use('/salary', salaryRouter);
apiRouter.use('/discount-cards', discountRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/client', clientRouter);
apiRouter.use('/export', exportsRouter);
apiRouter.use('/import', importsRouter);
